{
    'name': 'Proyecto F1',
    'version': '1.0',
    'summary': 'Gestión del Campeonato Mundial de Fórmula 1',
    'description': 'Módulo para gestionar escuderías, pilotos, carreras y clasificación.',
    'author': 'David Gómez Delicado',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/piloto_views.xml',
        'views/escuderia_views.xml',
        'views/carrera_views.xml',
        'views/clasificacion_views.xml',
        'wizard/add_piloto_wizard_view.xml',
        'views/menu_views.xml',
        'reports/report.xml',
    ],
    'installable': True,
    'application': True,
}